import type { LearningItem, Topic } from '../../domain/content-types.ts'
import { makeVariant } from './variant-factory.ts'

const basicVocabulary = [
  { id: 'wait', kind: 'word', english: 'wait', explanationEn: 'Stay in one place until it is your turn.', meaningCs: 'čekat', exampleEn: 'We wait for the bus.', partOfSpeech: 'verb' },
  { id: 'queue', kind: 'word', english: 'queue', explanationEn: 'A line of people waiting for something.', meaningCs: 'fronta', exampleEn: 'There is a long queue at the shop.', partOfSpeech: 'noun' },
  { id: 'long', kind: 'word', english: 'long', explanationEn: 'With a lot of space or time from one end to the other.', meaningCs: 'dlouhý', exampleEn: 'The queue is very long.', partOfSpeech: 'adjective' },
  { id: 'short', kind: 'word', english: 'short', explanationEn: 'With little space or time from one end to the other.', meaningCs: 'krátký', exampleEn: 'The queue is short today.', partOfSpeech: 'adjective' },
  { id: 'first', kind: 'word', english: 'first', explanationEn: 'Before all the other people or things.', meaningCs: 'první', exampleEn: 'The first person is at the front.', partOfSpeech: 'adjective' },
  { id: 'next', kind: 'word', english: 'next', explanationEn: 'After the person who is being served now.', meaningCs: 'další / na řadě', exampleEn: 'You are next in the queue.', partOfSpeech: 'adjective' },
] as const satisfies readonly LearningItem[]
const basicPhrases = [{ id: 'wait-in-a-queue', kind: 'phrase', english: 'wait in a queue', explanationEn: 'The common British English phrase for waiting in a queue.', meaningCs: 'čekat ve frontě (britská angličtina)', exampleEn: 'We wait in a queue at the shop.' }, { id: 'wait-in-line', kind: 'phrase', english: 'wait in line', explanationEn: 'The common American English phrase for waiting in a queue.', meaningCs: 'čekat ve frontě (americká angličtina)', exampleEn: 'We wait in line at the cinema.' }, { id: 'your-turn', kind: 'phrase', english: 'your turn', explanationEn: 'The time when you can do or receive something.', meaningCs: 'tvůj pořad / tvoje řada', exampleEn: 'It is your turn now.' }] as const satisfies readonly LearningItem[]
const basicStarters = [{ id: 'starter-queue', kind: 'sentence-starter', english: 'The queue is ___', explanationEn: 'Say what the queue is like.', meaningCs: 'Fronta je ___', exampleEn: 'The queue is long.' }] as const satisfies readonly LearningItem[]

const standardVocabulary = [
  { id: 'crowded', kind: 'word', english: 'crowded', explanationEn: 'Full of many people, with little free space.', meaningCs: 'přeplněný', exampleEn: 'The station is crowded during the morning rush.', partOfSpeech: 'adjective' },
  { id: 'patient', kind: 'word', english: 'patient', explanationEn: 'Able to wait calmly without becoming annoyed.', meaningCs: 'trpělivý', exampleEn: 'The patient passengers wait quietly.', partOfSpeech: 'adjective' },
  { id: 'impatient', kind: 'word', english: 'impatient', explanationEn: 'Annoyed because something is taking too long.', meaningCs: 'netrpělivý', exampleEn: 'Some customers become impatient after a long wait.', partOfSpeech: 'adjective' },
] as const satisfies readonly LearningItem[]
const standardPhrases = [{ id: 'move-forward', kind: 'phrase', english: 'move forward', explanationEn: 'Go closer to the front of the queue.', meaningCs: 'posunout se dopředu', exampleEn: 'Please move forward and leave a space.' }, { id: 'stand-behind', kind: 'phrase', english: 'stand behind', explanationEn: 'Wait after another person in the queue.', meaningCs: 'stát za někým', exampleEn: 'I stand behind the last person.' }, { id: 'wait-your-turn', kind: 'phrase', english: 'wait your turn', explanationEn: 'Wait politely until you are next.', meaningCs: 'počkat, až na tebe přijde řada', exampleEn: 'Everyone must wait their turn.' }] as const satisfies readonly LearningItem[]
const standardStarters = [{ id: 'starter-because-queue', kind: 'sentence-starter', english: 'People may become impatient because ___', explanationEn: 'Explain a possible reason for impatience.', meaningCs: 'Lidé mohou být netrpěliví, protože ___', exampleEn: 'People may become impatient because the queue is not moving.' }, { id: 'starter-should', kind: 'sentence-starter', english: 'People should ___ so that ___', explanationEn: 'Suggest polite queue behaviour and a result.', meaningCs: 'Lidé by měli ___, aby ___', exampleEn: 'People should wait their turn so that the queue is fair.' }] as const satisfies readonly LearningItem[]

const challengeVocabulary = [
  { id: 'frustrated', kind: 'word', english: 'frustrated', explanationEn: 'Upset or discouraged because progress is difficult or slow.', meaningCs: 'frustrovaný', exampleEn: 'Passengers look frustrated when the queue barely moves.', partOfSpeech: 'adjective' },
  { id: 'polite', kind: 'word', english: 'polite', explanationEn: 'Showing good manners and respect for other people.', meaningCs: 'zdvořilý', exampleEn: 'A polite request can prevent an argument.', partOfSpeech: 'adjective' },
  { id: 'considerate', kind: 'word', english: 'considerate', explanationEn: 'Thinking about how your actions affect other people.', meaningCs: 'ohleduplný', exampleEn: 'It is considerate to leave space for people to pass.', partOfSpeech: 'adjective' },
  { id: 'unfair', kind: 'word', english: 'unfair', explanationEn: 'Not treating people equally or according to the same rule.', meaningCs: 'nespravedlivý', exampleEn: 'It feels unfair when someone joins at the front.', partOfSpeech: 'adjective' },
] as const satisfies readonly LearningItem[]
const challengePhrases = [{ id: 'barely-moving', kind: 'phrase', english: 'barely moving', explanationEn: 'Moving so slowly that there is almost no progress.', meaningCs: 'téměř se neposouvající', exampleEn: 'The queue is barely moving.' }, { id: 'give-way', kind: 'phrase', english: 'give way', explanationEn: 'Let another person go before you.', meaningCs: 'dát přednost / pustit někoho před sebe', exampleEn: 'I gave way to an older passenger.' }] as const satisfies readonly LearningItem[]
const challengeStarters = [{ id: 'starter-impression-queue', kind: 'sentence-starter', english: 'The situation gives the impression that ___', explanationEn: 'Describe what a situation seems to show.', meaningCs: 'Situace působí dojmem, že ___', exampleEn: 'The situation gives the impression that the system is unfair.' }, { id: 'starter-although-queue', kind: 'sentence-starter', english: 'Although ___, people may ___', explanationEn: 'Show a contrast and a possible consequence.', meaningCs: 'Ačkoli ___, lidé mohou ___', exampleEn: 'Although most people are polite, some may become frustrated.' }] as const satisfies readonly LearningItem[]

const basic = makeVariant({
  learningGoal: 'I can describe a simple queue and say where people are in it.', vocabulary: basicVocabulary, phrases: basicPhrases, sentenceStarters: basicStarters,
  exampleSentences: ['The queue is long.', 'I wait in line at the cinema.', 'You are next in the queue.'], modelDescription: 'There is a long queue at the shop. I stand behind two people. The first person is at the front, and I am next after them.',
  buildTasks: [{ id: 'build-queue', template: 'The queue is ___.', suggestedItemIds: ['long', 'short', 'starter-queue'] }, { id: 'build-position', template: 'I stand behind ___.', suggestedItemIds: ['first', 'next', 'wait-in-line'] }], buildChecklist: ['I used a queue word.', 'I wrote a complete sentence.', 'I started with a capital letter.', 'I used a full stop.'],
  describeTask: { prompt: 'Describe a queue at a shop.', situation: 'Imagine a small shop with several people waiting. Say how the queue looks and where you are.', suggestedItemIds: ['wait', 'queue', 'long', 'short', 'first', 'next', 'starter-queue'], checklist: ['I used at least 3 queue words.', 'I said where a person is.', 'I wrote complete sentences.', 'I checked my full stops.'] },
  speakingTask: { prompt: 'Describe a queue you have seen.', preparationSeconds: 30, speakingSeconds: 45, suggestedItemIds: ['wait', 'queue', 'long', 'short', 'first', 'next'] },
  choice: { prompt: 'There are twelve people waiting. Nobody is near the front yet.', options: [{ id: 'long', text: 'long' }, { id: 'short', text: 'short' }, { id: 'first', text: 'first' }], correctOptionId: 'long', explanationEn: 'A long queue has many people or takes a lot of time.' },
  gap: { sentence: 'I am after the last person, so I am ___.', acceptedAnswers: ['next'], explanationEn: 'Next means after the person who is being served now.' },
  order: { tokens: [{ id: 'i', text: 'I' }, { id: 'wait', text: 'wait' }, { id: 'in', text: 'in' }, { id: 'line', text: 'line.' }], acceptedOrders: [['i', 'wait', 'in', 'line']], explanationEn: 'Wait in line is a common American English phrase; wait in a queue is common British English.' },
})
const standard = makeVariant({
  learningGoal: 'I can describe a queue, use useful everyday phrases, and explain why people may become impatient.', vocabulary: standardVocabulary, phrases: standardPhrases, sentenceStarters: standardStarters,
  exampleSentences: ['The crowded station makes it hard to see where the queue starts.', 'People should wait their turn so that the queue is fair.', 'Customers may become impatient because the queue is not moving.'], modelDescription: 'The station is crowded, and the queue is barely moving. Most passengers are patient, but some customers become impatient because they have been waiting for a long time. People should wait their turn and move forward when there is space.',
  buildTasks: [{ id: 'build-reason', template: 'People may become impatient because ___.', suggestedItemIds: ['impatient', 'crowded', 'wait-your-turn'] }, { id: 'build-fair', template: 'People should ___ so that ___.', suggestedItemIds: ['wait-your-turn', 'move-forward', 'stand-behind'] }], buildChecklist: ['I used a situation word accurately.', 'I explained a reason with because.', 'I used a useful queue phrase.', 'I checked that my ideas connect clearly.'],
  describeTask: { prompt: 'Describe a busy queue and its behaviour.', situation: 'Imagine a crowded station where a service is delayed. Describe the queue and explain how people may react.', suggestedItemIds: ['crowded', 'patient', 'impatient', 'move-forward', 'stand-behind', 'wait-your-turn', 'starter-because-queue', 'starter-should'], checklist: ['I described the setting and the queue.', 'I used at least 3 precise words.', 'I explained why people may react.', 'I included a polite suggestion.'] },
  speakingTask: { prompt: 'Explain what is happening in a busy queue.', preparationSeconds: 30, speakingSeconds: 60, suggestedItemIds: ['crowded', 'patient', 'impatient', 'move-forward', 'stand-behind', 'wait-your-turn'] },
  choice: { prompt: 'The queue has not moved for ten minutes, and people keep checking the time.', options: [{ id: 'impatient', text: 'impatient' }, { id: 'patient', text: 'patient' }, { id: 'crowded', text: 'crowded' }], correctOptionId: 'impatient', explanationEn: 'Impatient describes someone who is annoyed because something takes too long.' },
  gap: { sentence: 'Please ___ and leave room for the next person.', acceptedAnswers: ['move forward'], explanationEn: 'Move forward means go closer to the front of the queue.' },
  order: { tokens: [{ id: 'please', text: 'Please' }, { id: 'wait', text: 'wait' }, { id: 'your', text: 'your' }, { id: 'turn', text: 'turn.' }], acceptedOrders: [['please', 'wait', 'your', 'turn']], explanationEn: 'Wait your turn is a polite way to describe fair queue behaviour.' },
})
const challenge = makeVariant({
  learningGoal: 'I can give a nuanced impression of queue behaviour, describe frustration, and explain different reactions politely.', vocabulary: challengeVocabulary, phrases: challengePhrases, sentenceStarters: challengeStarters,
  exampleSentences: ['The queue is barely moving, so passengers look frustrated.', 'Although most people are polite, the situation gives the impression that the system is unfair.', 'It is considerate to give way when someone has a good reason to pass.'], modelDescription: 'The queue is barely moving, and the delay is clearly frustrating for some passengers. Although most people remain polite, the situation gives the impression that the system is unfair when one person joins near the front. Others may be more willing to give way if someone explains their reason calmly. Overall, the behaviour reflects both patience and growing frustration.',
  buildTasks: [{ id: 'build-impression', template: 'The situation gives the impression that ___, although ___.', suggestedItemIds: ['starter-impression-queue', 'unfair', 'polite', 'considerate'] }, { id: 'build-reaction', template: 'Although ___, people may ___ because ___.', suggestedItemIds: ['polite', 'frustrated', 'barely-moving', 'give-way'] }], buildChecklist: ['I described behaviour without exaggerating it.', 'I included a possible reason for frustration.', 'I used contrast or qualification.', 'I suggested a considerate response.'],
  describeTask: { prompt: 'Give a careful description of queue behaviour.', situation: 'Imagine a delayed service with a long queue. Discuss the atmosphere, the behaviour you can observe, and why different people may react differently.', suggestedItemIds: ['frustrated', 'polite', 'considerate', 'unfair', 'barely-moving', 'give-way', 'starter-impression-queue', 'starter-although-queue'], checklist: ['I used at least 4 precise expressions.', 'I described observable behaviour.', 'I explained more than one possible reaction.', 'I used a qualification or contrast.'] },
  speakingTask: { prompt: 'Discuss frustration and politeness in a queue.', preparationSeconds: 25, speakingSeconds: 75, suggestedItemIds: ['frustrated', 'polite', 'considerate', 'unfair', 'barely-moving', 'give-way'] },
  choice: { prompt: 'A passenger asks calmly if an elderly person can go first because they are tired.', options: [{ id: 'considerate', text: 'considerate' }, { id: 'unfair', text: 'unfair' }, { id: 'frustrated', text: 'frustrated' }], correctOptionId: 'considerate', explanationEn: 'Considerate behaviour thinks about how other people may be affected.' },
  gap: { sentence: 'The queue has barely moved for half an hour, so people feel ___.', acceptedAnswers: ['frustrated'], explanationEn: 'Frustrated describes being upset because progress is difficult or slow.' },
  order: { tokens: [{ id: 'although', text: 'Although' }, { id: 'the', text: 'the' }, { id: 'queue', text: 'queue' }, { id: 'is', text: 'is' }, { id: 'long', text: 'long,' }, { id: 'most', text: 'most' }, { id: 'people', text: 'people' }, { id: 'remain', text: 'remain' }, { id: 'polite', text: 'polite.' }], acceptedOrders: [['although', 'the', 'queue', 'is', 'long', 'most', 'people', 'remain', 'polite']], explanationEn: 'Although introduces a contrast between a difficult situation and a calm reaction.' },
})

export const queue: Topic = { id: 'waiting-in-a-queue', slug: 'waiting-in-a-queue', title: 'Waiting in a queue', category: 'situations', subcategory: 'waiting', shortDescription: 'Describe queues, everyday waiting, and polite reactions to delays.', variants: { basic, standard, challenge } }
