import type { LearningItem, Topic } from '../../domain/content-types.ts'
import { makeVariant } from './variant-factory.ts'

const basicVocabulary = [
  { id: 'happy', kind: 'word', english: 'happy', explanationEn: 'Feeling good and pleased.', meaningCs: 'šťastný / veselý', exampleEn: 'Her smile looks happy.', partOfSpeech: 'adjective' },
  { id: 'big', kind: 'word', english: 'big', explanationEn: 'Large and easy to notice.', meaningCs: 'velký', exampleEn: 'He has a big smile.', partOfSpeech: 'adjective' },
  { id: 'friendly', kind: 'word', english: 'friendly', explanationEn: 'Kind and welcoming to other people.', meaningCs: 'přátelský', exampleEn: 'Her friendly smile makes people feel welcome.', partOfSpeech: 'adjective' },
  { id: 'warm', kind: 'word', english: 'warm', explanationEn: 'Kind and pleasant in the feeling it gives.', meaningCs: 'vřelý', exampleEn: 'He gives us a warm smile.', partOfSpeech: 'adjective' },
  { id: 'beautiful', kind: 'word', english: 'beautiful', explanationEn: 'Very pleasing to look at.', meaningCs: 'krásný', exampleEn: 'She has a beautiful smile.', partOfSpeech: 'adjective' },
  { id: 'shy', kind: 'word', english: 'shy', explanationEn: 'Nervous or quiet with other people.', meaningCs: 'plachý / stydlivý', exampleEn: 'Her shy smile is small and quick.', partOfSpeech: 'adjective' },
] as const satisfies readonly LearningItem[]
const basicStarters = [{ id: 'starter-looks', kind: 'sentence-starter', english: 'Her / His smile looks ___', explanationEn: 'Describe what you can observe.', meaningCs: 'Její / jeho úsměv vypadá ___', exampleEn: 'Her smile looks warm.' }, { id: 'starter-seems', kind: 'sentence-starter', english: 'He / She seems ___', explanationEn: 'Use seems for a careful impression.', meaningCs: 'On / Ona působí ___', exampleEn: 'She seems happy.' }] as const satisfies readonly LearningItem[]

const standardVocabulary = [
  { id: 'cheerful', kind: 'word', english: 'cheerful', explanationEn: 'Noticeably happy and positive.', meaningCs: 'veselý / rozjařený', exampleEn: 'His cheerful smile brightens the room.', partOfSpeech: 'adjective' },
  { id: 'genuine', kind: 'word', english: 'genuine', explanationEn: 'Real and honestly felt, not pretended.', meaningCs: 'upřímný / opravdový', exampleEn: 'Her smile seems genuine.', partOfSpeech: 'adjective' },
  { id: 'welcoming', kind: 'word', english: 'welcoming', explanationEn: 'Making other people feel comfortable and accepted.', meaningCs: 'vlídný / přívětivý', exampleEn: 'The welcoming smile made it easy to enter the room.', partOfSpeech: 'adjective' },
  { id: 'relaxed', kind: 'word', english: 'relaxed', explanationEn: 'Calm and not worried or tense.', meaningCs: 'uvolněný', exampleEn: 'He looks relaxed when he smiles.', partOfSpeech: 'adjective' },
  { id: 'bright', kind: 'word', english: 'bright', explanationEn: 'Full of energy and positive feeling.', meaningCs: 'zářivý', exampleEn: 'She gave us a bright smile.', partOfSpeech: 'adjective' },
  { id: 'nervous', kind: 'word', english: 'nervous', explanationEn: 'Worried or unsure in a new situation.', meaningCs: 'nervózní', exampleEn: 'He seems a little nervous before the interview.', partOfSpeech: 'adjective' },
] as const satisfies readonly LearningItem[]
const standardStarters = [{ id: 'starter-appears', kind: 'sentence-starter', english: 'The smile appears ___ because ___', explanationEn: 'Describe an impression and explain it.', meaningCs: 'Úsměv působí ___, protože ___', exampleEn: 'The smile appears genuine because it reaches her eyes.' }, { id: 'starter-might', kind: 'sentence-starter', english: 'It might suggest ___, but ___', explanationEn: 'Separate an observation from a possible interpretation.', meaningCs: 'Může to naznačovat ___, ale ___', exampleEn: 'It might suggest confidence, but we cannot be certain.' }] as const satisfies readonly LearningItem[]

const challengeVocabulary = [
  { id: 'reassuring', kind: 'word', english: 'reassuring', explanationEn: 'Making someone feel less worried or uncertain.', meaningCs: 'uklidňující / dodávající jistotu', exampleEn: 'Her reassuring smile helped the child relax.', partOfSpeech: 'adjective' },
  { id: 'infectious', kind: 'word', english: 'infectious', explanationEn: 'So strong and positive that it makes other people feel the same.', meaningCs: 'nakažlivý / přenášející náladu', exampleEn: 'His infectious smile made everyone laugh.', partOfSpeech: 'adjective' },
  { id: 'subtle', kind: 'word', english: 'subtle', explanationEn: 'Small and not immediately easy to notice.', meaningCs: 'nenápadný / jemný', exampleEn: 'She gave a subtle smile across the table.', partOfSpeech: 'adjective' },
  { id: 'warm-hearted', kind: 'word', english: 'warm-hearted', explanationEn: 'Kind, generous, and caring towards other people.', meaningCs: 'srdečný / laskavý', exampleEn: 'His warm-hearted smile felt very sincere.', partOfSpeech: 'adjective' },
  { id: 'forced', kind: 'word', english: 'forced', explanationEn: 'Made to look real even though it may not feel natural.', meaningCs: 'vynucený / strojený', exampleEn: 'Her smile looked forced for the photograph.', partOfSpeech: 'adjective' },
  { id: 'hesitant', kind: 'word', english: 'hesitant', explanationEn: 'Showing that someone is unsure about what to do or say.', meaningCs: 'váhavý', exampleEn: 'He gave a hesitant smile before answering.', partOfSpeech: 'adjective' },
] as const satisfies readonly LearningItem[]
const challengeStarters = [{ id: 'starter-comes-across', kind: 'sentence-starter', english: 'The smile comes across as ___, although ___', explanationEn: 'Describe an impression while adding a qualification.', meaningCs: 'Úsměv působí ___, ačkoli ___', exampleEn: 'The smile comes across as reassuring, although we cannot know exactly how she feels.' }, { id: 'starter-first-impression', kind: 'sentence-starter', english: 'My first impression is that ___', explanationEn: 'Introduce a careful first interpretation.', meaningCs: 'Můj první dojem je, že ___', exampleEn: 'My first impression is that the smile is genuine.' }] as const satisfies readonly LearningItem[]

const basic = makeVariant({
  learningGoal: 'I can describe what a smile looks like and make a simple, careful impression.', vocabulary: basicVocabulary, sentenceStarters: basicStarters,
  exampleSentences: ['Her smile looks warm.', 'He has a big, friendly smile.', 'She seems happy, but I am not sure.'], modelDescription: 'The girl has a big, friendly smile. It looks warm and happy. She seems a little shy, but the smile makes her look kind.',
  buildTasks: [{ id: 'build-looks', template: 'Her smile looks ___.', suggestedItemIds: ['warm', 'friendly', 'happy'] }, { id: 'build-seems', template: 'He / She seems ___ because ___.', suggestedItemIds: ['shy', 'happy', 'beautiful'] }], buildChecklist: ['I described something I can see.', 'I used a personality or feeling word carefully.', 'I wrote a complete sentence.', 'I used a full stop.'],
  describeTask: { prompt: 'Describe a friendly smile.', situation: 'Imagine a person smiling at a new classmate. Describe the smile, then make one careful impression.', suggestedItemIds: ['big', 'friendly', 'warm', 'beautiful', 'shy', 'starter-looks', 'starter-seems'], checklist: ['I used at least 3 describing words.', 'I described the smile before making an impression.', 'I used seems or looks where helpful.', 'I checked my full stops.'] },
  speakingTask: { prompt: 'Describe a smile you remember.', preparationSeconds: 30, speakingSeconds: 45, suggestedItemIds: ['happy', 'big', 'friendly', 'warm', 'shy'] },
  choice: { prompt: 'The smile is small and the person looks down when people speak to her.', options: [{ id: 'shy', text: 'shy' }, { id: 'big', text: 'big' }, { id: 'beautiful', text: 'beautiful' }], correctOptionId: 'shy', explanationEn: 'Shy describes someone who may be quiet or nervous with other people.' },
  gap: { sentence: 'The smile is kind and pleasant. It looks ___.', acceptedAnswers: ['warm'], explanationEn: 'Warm can describe a kind and pleasant feeling.' },
  order: { tokens: [{ id: 'her', text: 'Her' }, { id: 'smile', text: 'smile' }, { id: 'looks', text: 'looks' }, { id: 'warm', text: 'warm.' }], acceptedOrders: [['her', 'smile', 'looks', 'warm']], explanationEn: 'Put the person or thing first, then looks, then the adjective.' },
})
const standard = makeVariant({
  learningGoal: 'I can describe a smile with more precise adjectives and separate what I see from what it might suggest.', vocabulary: standardVocabulary, sentenceStarters: standardStarters,
  exampleSentences: ['Her smile seems genuine because it reaches her eyes.', 'The welcoming smile makes the room feel relaxed.', 'It might suggest confidence, but we cannot be certain.'], modelDescription: 'The woman’s smile appears genuine and welcoming. It reaches her eyes, which gives it a relaxed quality. It might suggest that she feels comfortable, but a photograph cannot tell us exactly how she feels.',
  buildTasks: [{ id: 'build-appears', template: 'The smile appears ___ because ___.', suggestedItemIds: ['genuine', 'bright', 'welcoming'] }, { id: 'build-might', template: 'It might suggest ___, but ___.', suggestedItemIds: ['cheerful', 'relaxed', 'nervous', 'starter-might'] }], buildChecklist: ['I used a precise adjective.', 'I explained my observation.', 'I marked an interpretation as a possibility.', 'I checked my sentence structure.'],
  describeTask: { prompt: 'Describe the impression of a smile.', situation: 'Imagine a welcoming smile in a new place. Describe visible details and explain what they might suggest without treating your interpretation as a fact.', suggestedItemIds: ['cheerful', 'genuine', 'welcoming', 'relaxed', 'bright', 'nervous', 'starter-appears', 'starter-might'], checklist: ['I described an observable detail.', 'I used at least 3 precise words.', 'I used might or seems for an interpretation.', 'I explained one possible impression.'] },
  speakingTask: { prompt: 'Describe a smile and the feeling it may give.', preparationSeconds: 30, speakingSeconds: 60, suggestedItemIds: ['cheerful', 'genuine', 'welcoming', 'relaxed', 'bright', 'nervous'] },
  choice: { prompt: 'The smile looks natural and reaches the person’s eyes.', options: [{ id: 'genuine', text: 'genuine' }, { id: 'forced', text: 'forced' }, { id: 'nervous', text: 'nervous' }], correctOptionId: 'genuine', explanationEn: 'Genuine means real and honestly felt, not pretended.' },
  gap: { sentence: 'The person is calm and not tense. He looks ___.', acceptedAnswers: ['relaxed'], explanationEn: 'Relaxed describes someone who is calm and not worried or tense.' },
  order: { tokens: [{ id: 'it', text: 'It' }, { id: 'might', text: 'might' }, { id: 'suggest', text: 'suggest' }, { id: 'confidence', text: 'confidence,' }, { id: 'but', text: 'but' }, { id: 'we', text: 'we' }, { id: 'cannot', text: 'cannot' }, { id: 'know', text: 'know.' }], acceptedOrders: [['it', 'might', 'suggest', 'confidence', 'but', 'we', 'cannot', 'know']], explanationEn: 'Use might to make an interpretation careful rather than certain.' },
})
const challenge = makeVariant({
  learningGoal: 'I can give a nuanced description of a smile, distinguish observation from interpretation, and qualify my first impression.', vocabulary: challengeVocabulary, sentenceStarters: challengeStarters,
  exampleSentences: ['Her smile comes across as reassuring, although we cannot know exactly how she feels.', 'The subtle smile may be genuine, but the photograph gives us limited information.', 'His infectious smile changes the mood of the whole group.'], modelDescription: 'My first impression is that the smile is subtle but reassuring. It does not look forced; instead, it comes across as warm-hearted and genuine. However, we should not assume that the person is happy simply because of one expression. The image gives an impression, not proof of an inner feeling.',
  buildTasks: [{ id: 'build-qualified', template: 'The smile comes across as ___, although ___.', suggestedItemIds: ['reassuring', 'subtle', 'warm-hearted', 'hesitant'] }, { id: 'build-cautious', template: 'My first impression is that ___, but ___.', suggestedItemIds: ['warm-hearted', 'forced', 'hesitant', 'subtle'] }], buildChecklist: ['I used nuanced vocabulary.', 'I distinguished observation from interpretation.', 'I added a qualification or contrast.', 'I avoided presenting an inner feeling as certain.'],
  describeTask: { prompt: 'Give a careful interpretation of a smile.', situation: 'Imagine a photograph of someone smiling during a difficult conversation. Describe the visible expression and discuss more than one possible interpretation.', suggestedItemIds: ['reassuring', 'infectious', 'subtle', 'warm-hearted', 'forced', 'hesitant', 'starter-comes-across', 'starter-first-impression'], checklist: ['I used at least 4 nuanced words.', 'I separated what is visible from what is inferred.', 'I included a qualification or alternative.', 'I avoided claiming to know the person’s exact feeling.'] },
  speakingTask: { prompt: 'Give a nuanced description of a smile.', preparationSeconds: 25, speakingSeconds: 75, suggestedItemIds: ['reassuring', 'infectious', 'subtle', 'warm-hearted', 'forced', 'hesitant'] },
  choice: { prompt: 'The expression is small and uncertain, and the person looks away before smiling.', options: [{ id: 'hesitant', text: 'hesitant' }, { id: 'infectious', text: 'infectious' }, { id: 'reassuring', text: 'reassuring' }], correctOptionId: 'hesitant', explanationEn: 'Hesitant suggests uncertainty about what to do or say.' },
  gap: { sentence: 'The smile seems kind and calming, but this is only an impression. It is ___.', acceptedAnswers: ['reassuring'], explanationEn: 'Reassuring describes something that makes people feel less worried.' },
  order: { tokens: [{ id: 'we', text: 'We' }, { id: 'cannot', text: 'cannot' }, { id: 'know', text: 'know' }, { id: 'exactly', text: 'exactly' }, { id: 'how', text: 'how' }, { id: 'she', text: 'she' }, { id: 'feels', text: 'feels.' }], acceptedOrders: [['we', 'cannot', 'know', 'exactly', 'how', 'she', 'feels']], explanationEn: 'This sentence clearly separates an observation from a person’s unknown inner feeling.' },
})

export const smile: Topic = { id: 'smile', slug: 'smile', title: 'Describing a smile', category: 'people', subcategory: 'smile', shortDescription: 'Describe a smile and make careful observations about the impression it gives.', variants: { basic, standard, challenge } }
